# Site settings
author: Randy Taylor
title: Think Outside the Block
header-img: img/home-bg.png
email: randyisbusy@gmail.com
copyright_name: Randy Taylor
description: > # this means to ignore newlines until "baseurl:"
  new.map{ |u| expert = u * experience}
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rhtaylor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
